### ISSUE TITLE
inquiry for building linux arm target with crashpad

### ISSUE THREAD

**Issue by austinlin7732** [getsentry/crashpad-build#9]
Does crashpad support linux arm target ?

1. I config target_cup with `gn args out/Default`
![image](https://user-images.githubusercontent.com/50258355/64097471-ead31000-cd96-11e9-8e5e-88c44d56e60a.png)

2.  start to build by ninja
`ninja -C out/Default`

3. Result, will build fail
![image](https://user-images.githubusercontent.com/50258355/64097625-62a13a80-cd97-11e9-999d-a6da228feb99.png)

**Comment by tonyo** [comment]
We haven't tested building it on ARM; it's better to ask Crashpad folks directly: https://chromium.googlesource.com/crashpad/crashpad/

Also, FYI: this repository will be archived soon, the development will continue in https://github.com/getsentry/sentry-native
